---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flaky
  namespace: demo
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: flaky
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flaky
  namespace: demo
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: flaky
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaky
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaky
  template:
    metadata:
      labels:
        app: flaky
    spec:
      containers:
        - name: flaky
          image: ${IMAGE}
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            periodSeconds: 5
            initialDelaySeconds: 5
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            periodSeconds: 5
            initialDelaySeconds: 5
            timeoutSeconds: 3
          env:
            - name: MY_ENV
              value: 12factor
